### ISSUE TITLE
Portality and Titanium failed to load correctly

### ISSUE THREAD

**Issue by clevi4** [Buuz135/Portality#57] opened 2019-09-09 23:18 UTC
Error screen mentions net/minecraftforge/fluids/FluidTank for both errors. See attachments
Minecraft 1.14.4 Forge 28.0.91 

![Annotation 2019-09-09 171337](https://user-images.githubusercontent.com/47880858/64572651-74e62000-d325-11e9-865f-4d1e9b2a0404.png)
[latest.log](https://github.com/InnovativeOnlineIndustries/Portality/files/3592947/latest.log)

**Comment by raziel23x** [comment] 2019-09-10 11:35
duplicate of https://github.com/InnovativeOnlineIndustries/Portality/issues/56

**Closed as completed** 2019-09-10 11:39 UTC
Labels: duplicate
