### ISSUE TITLE
NO GUI on Portal Controller

### ISSUE THREAD

**Issue by WheezerX** [Buuz135/Portality#61] opened 2019-10-23 21:17 UTC
Mod won't load the portality controller. Minecraft 1.14.4, Forge .61

When placing the portal controller in the appropriate center space, server spits this error, and the error repeats when attempting to load the GUI by right clicking the controller.

[23Oct2019  21:13:21.459] [Server thread/FATAL]  [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted  to load class net/minecraft/client/resources/I18n for invalid dist  DEDICATED_SERVER
--
[23Oct2019  21:13:21.460] [Server thread/FATAL]  [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing  task on Server
java.lang.RuntimeException: Attempted to load class net/minecraft/client/resources/I18n for invalid dist DEDICATED_SERVER
at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClass(RuntimeDistCleaner.java:71) ~[forge-1.14.4-28.1.61.jar:28.1]
at  cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClass(ILaunchPluginService.java:102)  ~odlauncher-4.1.0.jar:4.1.0+62+5bfa59b]
at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:80) ~odlauncher-4.1.0.jar:?]
at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115) ~odlauncher-4.1.0.jar:?]
at  cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:241)  ~odlauncher-4.1.0.jar:?]
at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:128) ~odlauncher-4.1.0.jar:?]
at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~odlauncher-4.1.0.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
at com.buuz135.portality.block.BlockController.func_220051_a(BlockController.java:103) ~[?:?]
at net.minecraft.block.BlockState.func_215687_a(BlockState.java:274) ~[?:?]
at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:323) ~[?:?]
at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:847) ~[?:?]
at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?]
at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?]
at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699) [?:?]
at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693) [?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:678) [?:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626) [?:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

**Comment by Rakambda** [comment] 2019-10-24 17:43
Duplicate of #58 I guess

**Comment by Buuz135** [comment] 2019-10-25 13:56
Fixed in released version 2.0.4

**Closed as completed by Buuz135** 2019-10-25 13:56 UTC
